# Generated by Django 3.1.7 on 2021-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
